---
title: "CoxPH"
author: "Amy Watt"
date: "4/12/2019"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
aids <- read.csv("AIDSdata.csv")
library(tidyverse)
library(ggplot2)
library(survival)
library(survminer)
```

```{r, echo=FALSE}
#Changing data from numerical to text
aids$censor_text <- NA
aids$censor_d_text <- NA
aids$txgrp_text <- NA
aids$strat2_text <- NA
aids$sex_text <- NA
aids$raceth_text <- NA
aids$ivdrug_text <- NA
aids$hemophil_text <- NA

#Adding a new column in dataframe for combined sex/raceth demographics.

aids$demo <- NA
aids$demo_text <- NA
```

```{r, echo=FALSE}
for (elt in 1:length(aids$id)) {
  s = toString(aids$sex[elt])
  r = toString(aids$raceth[elt])
  aids$demo[elt] <- as.numeric(paste (s, r, sep=''))
  
  if (aids$censor[elt] == 1) {
    aids$censor_text[elt] <- 'AIDS/death'
  } else {
    aids$censor_text[elt] <- 'Otherwise'
  }
  
  if (aids$censor_d[elt] == 1) {
    aids$censor_d_text[elt] <- 'Death'
  } else {
    aids$censor_d_text[elt] <- 'Otherwise'
  }
  
  if (aids$txgrp[elt] == 1) {
    aids$txgrp_text[elt] <- 'Placebo'
  } else {
    aids$txgrp_text[elt] <- 'IDV'
  }
  
  if (aids$strat2[elt] == 1) {
    aids$strat2_text[elt] <- 'CD4 <= 50'
  } else {
    aids$strat2_text[elt] <- 'CD4 > 50'
  }
  
  if (aids$sex[elt] == 1) {
    aids$sex_text[elt] <- 'Male'
  } else {
    aids$sex_text[elt] <- 'Female'
  }
  
  if (aids$raceth[elt] == 1) {
    aids$raceth_text[elt] <- 'White Non-Hispanic'
  } else if (aids$raceth[elt] == 2) {
    aids$raceth_text[elt] <- 'Black Non-Hispanic'
  } else if (aids$raceth[elt] == 3) {
    aids$raceth_text[elt] <- 'Hispanic'
  } else if (aids$raceth[elt] == 4) {
    aids$raceth_text[elt] <- 'Asian/Pacific Islander'
  } else if (aids$raceth[elt] == 5) {
    aids$raceth_text[elt] <- 'American Indian/Alaskan Native'
  } else if (aids$raceth[elt] == 6) {
    aids$raceth_text[elt] <- 'Other/Unknown'
  }
  
  if (aids$ivdrug[elt] == 1) {
    aids$ivdrug_text[elt] <- 'Never'
  } else if (aids$ivdrug[elt] == 2) {
    aids$ivdrug_text[elt] <- 'Currently'
  } else if (aids$ivdrug[elt] == 3) {
    aids$ivdrug_text[elt] <- 'Previously'
  }
  
  if (aids$hemophil[elt] == 1) {
    aids$hemophil_text[elt] <- 'Yes'
  } else if (aids$hemophil[elt] == 0) {
    aids$hemophil_text[elt] <- 'No'
  }
  
  aids$demo_text[elt] <- (paste (aids$sex_text[elt], aids$raceth_text[elt], sep=', '))
}
```  

```{r}
KM <- survfit(Surv(time, censor)~1, data=aids)
survminer::ggsurvplot(KM, conf.int=TRUE, censor=F) + ggtitle("Overall Survival Curve")
```
```{r}
KM <- survfit(Surv(time, censor)~karnof, type="kaplan-meier", conf.type="log", data=aids)
survminer::ggsurvplot(KM, conf.int=FALSE, censor=F) + ggtitle("Survival Curve by Karnofsky Scale")
```

